### ISSUE TITLE
Question about the reports

### ISSUE THREAD

**Issue by ze6killer** [oPromessa/flickr-uploader#38]
Hi,

Sorry, some more questions. This should be easier though.

As output of the script I can read the following:
```
...
 Initial Found Files:[   757]
          - Bad Files:[     7] = [   750]
          Note: some Bad files may no longer exist!
Photos count:
                Local:[   752]
               Flickr:[  6582]
Not in sets on Flickr:[   410]
 [32m[1369][2018.02.11 13:55:15]:[14886      ] [0m[PRINT   ]:[uploadr] --------- (V2.6.7) End time: 2018.02.11 13:55:15 ---------
```

What does **bad files** mean please? :)

Thanks for all the good work!

Kind Regards,
Ze

**Comment by oPromessa** [comment]
Check the explanation for "badfiles" on ["Usage Arguments"](https://github.com/oPromessa/flickr-uploader#usageargumentsoptions).

Also discussed on issue #27. 

Flickr "rejects" some files due to their type. So, instead of continuously attempting to load them on each run, the tool saves them and it bypasses them.

An upcoming version will also cater for "Error 8: File is too large" discussed on issue #37.

Anyhow you can:
- disable this control.check by **not using** the -b option.
- if, from time to time, you want to "reset" and re-attempt to upload such files, you can use the  "-c" option to cleanup such badflies.

Further notice on your example output:
- Local should yield 750 but this number may be off by 1 or 2. Still figuring it out to fix it.
- I've also noticed that the Flickr number reported by flickr as the number of pics found on flickr is sometimes off by 1. Can't to much here as this is the number returned by flickr itself.
- Finally "Not in sets on Flickr" indicates just that. It's a pointer to some error, as **all** uploaded pics by uploadr should be on an Album. What I do normally do is to delete such pics from Flickr directly from the flickr/organize interface. But I've seen other users which have other tools uploading pics to Flickr ignore this number.

**Comment by ze6killer** [comment]
Hi,

thanks for the explanationS. I'll follow on this other thread then to not mix things up too much.

Ze
